### ISSUE TITLE
Make imports local

### ISSUE THREAD

**Issue by jchodera** [choderalab/covid-moonshot-ml#12]
In order to make it easier to reuse modules, it's helpful to make imports as local as possible.
If we `import` a package just before we need to use it within a method, it becomes possible to import a module from this repo even if some of the methods require packages that are not yet installed.

**Comment by jchodera** [comment]
Just to clarify: I'm running into difficulty running the CDD downloader script because it also needs pytorch, and I'm having issues with the `pytorch` from the `pytorch` channel:
```
$ python scripts/download_moonshot_data.py -o achiral-racemic.csv -key MjA0MHxwa0daTWExNnE4VGJJYkw2QkJGaDN5ZDR3QnhxS0JQS1ZvZVZJVG0zRWYxN3llWkkzdz09
Traceback (most recent call last):
  File "/lila/home/chodera/github/choderalab/covid-moonshot-ml/scripts/download_moonshot_data.py", line 6, in <module>
    from covid_moonshot_ml.datasets.moonshot import download_molecules
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/covid_moonshot_ml/__init__.py", line 8, in <module>
    from . import nn
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/covid_moonshot_ml/nn/__init__.py", line 1, in <module>
    from .models import *
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/covid_moonshot_ml/nn/models/__init__.py", line 2, in <module>
    from .SchNetBind import SchNetBind
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/covid_moonshot_ml/nn/models/SchNetBind.py", line 2, in <module>
    from torch_geometric.nn import SchNet
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 9, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 15, in <module>
    torch.ops.load_library(spec.origin)
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /lila/home/chodera/miniconda/envs/moonshotml/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so)
```
If we can avoid having to import libraries until they're needed, this will make it much easier to use tools even if all dependencies aren't installed.

There are cases (as with `SchNet`) where we must import at file level a class we will then subclass, but we can avoid importing everything into the namespace until it's needed.
